/**
 * Save Environment Configuration API
 * Allows the installation wizard to save .env file
 */

import { NextResponse } from 'next/server'
import { writeFileSync, existsSync } from 'fs'
import { join } from 'path'
import { randomBytes } from 'crypto'

export async function POST(req: Request) {
    try {
        const body = await req.json()
        const {
            dbHost = 'localhost',
            dbPort = '3306',
            dbUser = 'root',
            dbPassword = '',
            dbName = 'wordpress_manager',
            recaptchaSiteKey = '',
            recaptchaSecretKey = '',
            smtpHost = '',
            smtpPort = '587',
            smtpUser = '',
            smtpPassword = '',
            smtpFromEmail = '',
            smtpFromName = 'WP Manager'
        } = body

        // Generate secure keys automatically
        const encryptionKey = randomBytes(32).toString('hex')
        const jwtSecret = randomBytes(32).toString('base64')
        const sessionSecret = randomBytes(32).toString('base64')

        const envContent = `# ===========================================
# WordPress Site Manager - Environment Config
# Generated by Installation Wizard
# ===========================================

# Database Configuration
DB_HOST=${dbHost}
DB_PORT=${dbPort}
DB_USER=${dbUser}
DB_PASSWORD=${dbPassword}
DB_NAME=${dbName}

# Security Keys (AUTO-GENERATED - DO NOT SHARE)
ENCRYPTION_KEY=${encryptionKey}
JWT_SECRET=${jwtSecret}
SESSION_SECRET=${sessionSecret}

# reCAPTCHA v3 (Optional)
RECAPTCHA_SITE_KEY=${recaptchaSiteKey}
RECAPTCHA_SECRET_KEY=${recaptchaSecretKey}

# Email SMTP Configuration (Optional)
SMTP_HOST=${smtpHost}
SMTP_PORT=${smtpPort}
SMTP_USER=${smtpUser}
SMTP_PASSWORD=${smtpPassword}
SMTP_FROM_EMAIL=${smtpFromEmail}
SMTP_FROM_NAME=${smtpFromName}

# Application Settings
NEXT_PUBLIC_APP_URL=http://localhost:3000
NODE_ENV=development

# Beta Site Pattern (regex for beta/staging domains)
BETA_SITE_PATTERN=\\.gogroth\\.com$
`

        const envPath = join(process.cwd(), '.env')

        // Check if .env already exists and has content
        if (existsSync(envPath)) {
            // Create backup
            const backupPath = join(process.cwd(), '.env.backup')
            const existingContent = require('fs').readFileSync(envPath, 'utf8')
            writeFileSync(backupPath, existingContent)
        }

        writeFileSync(envPath, envContent)

        return NextResponse.json({
            success: true,
            message: 'Configuration saved successfully',
            note: 'Security keys have been auto-generated'
        })

    } catch (error) {
        console.error('[Save Config] Error:', error)
        return NextResponse.json(
            { error: 'Failed to save configuration' },
            { status: 500 }
        )
    }
}
